'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Card, ErrorNotice } from '@/components/primitives';
import type { TargetAnalysis } from '@/lib/ai/analyse-target';
import { titleCase } from '@/lib/utils';

export function AiAssessment({
  companyNumber,
  analysis,
  model,
}: {
  companyNumber: string;
  analysis: TargetAnalysis | null;
  model: string | null;
}) {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function analyse() {
    setBusy(true);
    setError(null);
    try {
      const response = await fetch(`/api/company/${companyNumber}/analyse`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({}),
      });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload.error ?? 'Analysis failed.');
      router.refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  }

  return (
    <Card
      title="AI assessment"
      action={
        <button className="btn-secondary py-1" disabled={busy} onClick={() => void analyse()}>
          {busy ? 'Analysing…' : analysis ? 'Re-analyse' : 'Analyse'}
        </button>
      }
    >
      {error && (
        <div className="p-3">
          <ErrorNotice title="Analysis failed" detail={error} />
        </div>
      )}

      {!analysis ? (
        <p className="px-4 py-4 text-sm text-ink-muted">
          Save this company as a target and run an analysis to get a written assessment. The analysis interprets the
          stored filings — it never invents figures.
        </p>
      ) : (
        <div className="divide-y divide-line">
          <div className="px-4 py-3">
            <span className="rounded border border-accent/40 bg-accent-soft px-2 py-0.5 text-xs font-semibold text-accent">
              {titleCase(analysis.overall_assessment)}
            </span>
            <p className="mt-2 text-sm">{analysis.summary}</p>
          </div>

          <Prose title="Financial analysis" body={analysis.financial_analysis} />
          <Prose title="Ownership" body={analysis.ownership_analysis} />
          <Prose title="Succession signals" body={analysis.succession_analysis} />

          <List title="Risks" items={analysis.risks} tone="text-bad" />
          <List title="Unknowns" items={analysis.unknowns} tone="text-ink-muted" />
          <List title="Questions to investigate" items={analysis.questions_to_investigate} tone="text-ink" />

          <Prose title="Recommended next step" body={analysis.recommended_next_step} />
          <Prose title="Outreach angle" body={analysis.outreach_angle} />

          {model && <p className="px-4 py-2 text-[11px] text-ink-faint">Generated by {model}.</p>}
        </div>
      )}
    </Card>
  );
}

function Prose({ title, body }: { title: string; body: string }) {
  if (!body) return null;
  return (
    <div className="px-4 py-3">
      <h3 className="label">{title}</h3>
      <p className="mt-1 text-sm text-ink-muted">{body}</p>
    </div>
  );
}

function List({ title, items, tone }: { title: string; items: string[]; tone: string }) {
  if (items.length === 0) return null;
  return (
    <div className="px-4 py-3">
      <h3 className="label">{title}</h3>
      <ul className={`mt-1 list-disc space-y-1 pl-5 text-sm ${tone}`}>
        {items.map((item, index) => (
          <li key={index}>{item}</li>
        ))}
      </ul>
    </div>
  );
}
